site_name: Pipeline 2.0.0
theme: readthedocs
markdown_extensions:
  - admonition
pages:
- Overview: 'index.md'
- Quick start: 'start.md'
- Projects manager: 'projects.md'
- The Navigation panel: 'nav.md'
- Components: 'component.md'
- Pipeline menu: 'menu.md'
- Presets: 'presets.md'